"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// meta 는 서버 클라이언트에서 사용 가능.
// export const metadata = {
//   title: "Web tutorials",
//   description: "Generated by dy",
// };

export default function RootLayout({ children }) {
  const[topics, setTopics] = useState([]);
  // 아래의 useEffect 사용시 npx json-server --port 9999 --watch db.json 를 실행.
  useEffect(()=> {
    fetch('http://localhost:9999/topics')
      .then(resp=>resp.json())
      .then(result=>{
        setTopics(result);
      });
      // 빈 배열은 한번만 작동하기 위함
  }, []);
  return (
    <html >
      <body >
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic)=> {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
