import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// meta 는 서버 클라이언트에서 사용 가능.
export const metadata = {
  title: "Web tutorials",
  description: "Generated by dy",
};

export default async function RootLayout({ children }) {
  // 서버컴퍼넌트는 서버쪽에서 fetch메소드 실행 끝날 때까지 await, 끝나면 json으로 바뀜
  // 용량이 적어지고, 같은 서버일 경우 빠르게 이동작이 끝남. 
  const resp = await fetch('http://localhost:9999/topics'); 
  const topics = await resp.json();
  return (
    <html >
      <body >
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic)=> {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
